name: do nothing

on:
  pull_request:

jobs:
  run-test:
    name: Run test
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test
        run: |
          echo "Run test"
