name: do nothing

on:
  pull_request:
    types: [ opened ]

jobs:
  run-test:
    name: Run test
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Run test
        run: |
          echo "Hello, World!"
          echo "Running test..."
