name: open-pr-ci-completed

on:
  workflow_run:
    workflows: ["lint text"]
    types: [completed]
  workflow_dispatch:

jobs:
  open-pr-ci-completed:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # - run: cat $GITHUB_EVENT_PATH
      # sha から pull request number を特定する
      - name: Get associated pull request
        id: get_pull_request
        run: |
          PR=$(gh api repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_sha || github.sha }}/pulls | jq '.[0]')
          PR_NUM=$(echo $PR | jq '.number')
          LABELS=$(echo $PR | jq -r '.labels[].name')
          DRAFT=$(echo $PR | jq '.draft')
          echo "number=$PR_NUM" >> $GITHUB_OUTPUT
          echo "labels=$LABELS" >> $GITHUB_OUTPUT
          echo "draft=$DRAFT" >> $GITHUB_OUTPUT
      # このPRに'ci-test'というlabelがついているかどうかを確認する
      - name: Get labels
        id: get_labels
        run: |
          LABEL_NAME="ci-test"
          if [[ ${{ steps.get_pull_request.outputs.labels }} == *"$LABEL_NAME"* ]]; then
            echo "Label $LABEL_NAME found"
            echo "CONTINUE=true" >> $GITHUB_OUTPUT
          else
            echo "Label $LABEL_NAME not found"
            echo "CONTINUE=false" >> $GITHUB_OUTPUT
          fi
      # そのPRの全てのCIのステータスを取得する
      - name: Get all checks status
        if: steps.get_labels.outputs.CONTINUE == 'true'
        id: get_checks_status
        uses: actions/github-script@v6
        with:
          script: |
            const res = await github.rest.checks.listForRef({
              owner: "${{ github.event.repository.owner.login }}",
              repo: "${{ github.event.repository.name }}",
              ref: "${{ github.sha }}",
            })
            console.log(JSON.stringify(res, null, "\t"))
            core.setOutput("checks", res.data.check_runs.filter(check => check.name !== "open-pr-ci-completed"))
      # get_checks_status の output が全て success なら、PRをopenにする
      - name: Ready for review this pull request
        if: ${{ success() && steps.get_pull_request.outputs.draft != 'false' && (steps.get_checks_status.outputs.checks.length == 0 || steps.get_checks_status.outputs.checks.*.status == 'completed') }}
        run: gh pr ready ${{ steps.get_pull_request.outputs.number }} -R ${{ github.repository }}
        
