name: open-pr-ci-completed

on:
  status:
  workflow_dispatch:

jobs:
  open-pr-ci-completed:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # - run: cat $GITHUB_EVENT_PATH
      # sha から pull request number を特定する
      - name: Get pull request number
        id: get_pull_request_number
        uses: actions/github-script@v6
        with:
          script: |
            const res = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: "${{ github.event.repository.owner.login }}",
              repo: "${{ github.event.repository.name }}",
              commit_sha: "${{ github.sha }}",
            })
            console.log(JSON.stringify(res, null, "\t"))
            core.setOutput("pull_request_number", res.data[0].number)

      # このPRに'ci-test'というlabelがついているかどうかを確認する
      - name: Get labels
        id: get_labels
        run: |
          LABEL_NAME="ci-test"
          PR_NUMBER=${{ steps.get_pull_request_number.outputs.pull_request_number }}
          LABELS=$(gh pr view $PR_NUMBER -R ${{ github.repository }} --json labels -q '.labels[].name')
          if [[ $LABELS == *"$LABEL_NAME"* ]]; then
            echo "Label $LABEL_NAME found"
            echo "CONTINUE=true" >> $GITHUB_ENV
          else
            echo "Label $LABEL_NAME not found"
            echo "CONTINUE=false" >> $GITHUB_ENV
          fi
      # そのPRの全てのCIのステータスを取得する
      - name: Get all checks status
        if: steps.get_labels.outputs.CONTINUE == 'true'
        id: get_checks_status
        uses: actions/github-script@v6
        with:
          script: |
            const res = await github.rest.checks.listForRef({
              owner: "${{ github.event.repository.owner.login }}",
              repo: "${{ github.event.repository.name }}",
              ref: "${{ github.sha }}",
            })
            console.log(JSON.stringify(res, null, "\t"))
            core.setOutput("checks", res.data.check_runs.filter(check => check.name !== "open-pr-ci-completed"))
      # get_checks_status の output が全て success なら、PRをopenにする
      - name: Ready for review this pull request
        if: ${{ steps.get_labels.outputs.CONTINUE == 'true' && steps.get_checks_status.outputs.checks.length == 0 || steps.get_checks_status.outputs.checks.*.status == 'completed' }}
        run: gh pr ready ${{ steps.get_pull_request_number.outputs.pull_request_number }} -R ${{ github.repository }}
        