name: open-pr-ci-completed

on:
  status:
  # workflow_dispatch:

jobs:
  open-pr-ci-completed:
    runs-on: ubuntu-latest
    # そのPRのCIが全て成功したら、PRをopenにする
    # 'ci-test'のついたPRのCIが全て成功したら、PRをopenにする
    if: github.event.state == 'success' && contains(github.event.context.labels.*.name, 'ci-test')
    steps:
      # そのPRの全てのCIのステータスを取得する
      - name: Get all checks status
        id: get_checks_status
        uses: actions/github-script@v3
        with:
          script: |
            const response = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });
            return response.data.check_runs.map(check => check.conclusion);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # get_checks_status の output が全て success なら、PRをopenにする
      - name: Open this pull request
        if: ${{ join(steps.get_checks_status.outputs.* == 'success', ' && ') }}
        uses: actions/github-script@v3
        with:
          script: |
            github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              state: 'open'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
