name: open-pr-ci-completed

on:
  # pull_request:
  #   types: [labeled]
  check_suite:
    types: [completed]

jobs:
  open-pr-ci-completed:
    runs-on: ubuntu-latest
    if: github.event.check_suite.conclusion == 'success' && contains(github.event.check_suite.pull_requests[0].labels.*.name, 'ci-test')
    steps:
      # - name: get pr label
      #   id: get_pr_label
      #   uses: actions/github-script@v3
      #   with:
      #     script: |
      #       const pr = await github.pulls.get({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         pull_number: context.payload.check_suite.pull_requests[0].number
      #       });
      #       return pr.data.labels[0].name;
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Open this pull request
        uses: peter-evans/open-pull-request@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.check_suite.head_branch }}
          # title: ${{ github.event.check_suite.pull_requests[0].title }}
          # body: ${{ github.event.check_suite.pull_requests[0].body }}
          # labels: ${{ github.event.check_suite.pull_requests[0].labels.*.name }}
          draft: false
          # delete_branch: false

