name: open-pr-ci-completed

on:
  status:
  workflow_dispatch:

jobs:
  open-pr-ci-completed:
    runs-on: ubuntu-latest
    steps:
      # 'ci-test'というlabelのついたPRのCIが全て成功したら、PRをopenにする
      - name: Get labels
        id: get_labels
        uses: actions/github-script@v3
        with:
          script: |
            const response = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            return response.data.filter(pull => pull.labels.some(label => label.name === 'ci-test'));
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # PRがない場合は終了
      - name: Exit if no pull request
        if: steps.get_labels.outputs.result.length == 0
        run: exit 0
      # そのPRの全てのCIのステータスを取得する
      - name: Get all checks status
        id: get_checks_status
        uses: actions/github-script@v3
        with:
          script: |
            const response = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });
            return response.data.check_runs.map(check => check.conclusion);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # get_checks_status の output が全て success なら、PRをopenにする
      - name: Open this pull request
        if: ${{ join(steps.get_checks_status.outputs.* == 'success', ' && ') }}
        uses: actions/github-script@v3
        with:
          script: |
            github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              state: 'open'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
