name: workflow dispatch boolean inputs

on:
  workflow_dispatch:
    inputs:
      boolean_input:
        description: 'A boolean input'
        type: boolean
        required: true
        default: true

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GITHUB_EVENT_BOOLEAN_INPUT: ${{ github.event.inputs.boolean_input }}
      INPUTS_BOOLEAN_INPUT: ${{ inputs.boolean_input }}
    steps:
      - name: Check value
        run: |
          echo "GITHUB_EVENT_BOOLEAN_INPUT is: $GITHUB_EVENT_BOOLEAN_INPUT"
          echo "INPUTS_BOOLEAN_INPUT is: $INPUTS_BOOLEAN_INPUT"

      - name: Run if github.event.inputs.boolean_input
        if: ${{ github.event.inputs.boolean_input }}
        run: |
          echo "github.event.inputs.boolean_input is true"
      - name: Run if inputs.boolean_input
        if: ${{ inputs.boolean_input }}
        run: |
          echo "inputs.boolean_input is true"


      - name: Don't run if github.event.inputs.boolean_input
        if: ${{ ! github.event.inputs.boolean_input }}
        run: |
          echo "github.event.inputs.boolean_input is true"
      - name: Don't run if inputs.boolean_input
        if: ${{ ! inputs.boolean_input }}
        run: |
          echo "inputs.boolean_input is true"

      - name: Run if github.event.inputs.boolean_input == 'true'
        if: ${{ github.event.inputs.boolean_input == 'true' }}
        run: |
          echo "github.event.inputs.boolean_input == 'true' is true"
      - name: Run if inputs.boolean_input == 'true'
        if: ${{ inputs.boolean_input == 'true' }}
        run: |
          echo "inputs.boolean_input == 'true' is true"
